# MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/ai_interview_db
spring.datasource.username=root
spring.datasource.password=MySql@2005
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Gemini API
gemini.api.key=AIzaSyC6dXB50HCSJSVXXO-Yf1MWJfIFQ7OZU2o
gemini.api.url=https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent
# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true